# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  hworld:
    docker:
    steps:
      - checkout
      - run: echo "Hello World"
  name:
    docker:
    steps:
      - checkout
      - run: echo "My name is Pravin Rai"
workflows:
  version: 2
  build_and_test:
    jobs:
      - hworld
      - name
