version: 2
jobs:
  name:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "My name is Pravin Rai"
  office:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "I work in Capgemini"
workflows:
  version: 2
  name_and_office:
    jobs:
      - name
      - office
